package com.example.matrix_events.managers;

import android.util.Log;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;

import com.example.matrix_events.database.DBConnector;
import com.example.matrix_events.database.DBListener;
import com.example.matrix_events.entities.Profile;
import com.example.matrix_events.mvc.Model;

import java.util.ArrayList;
import java.util.List;

/**
 * Manages all user profile data and operations within the application.
 * <p>
 * This class follows the <b>Singleton Pattern</b> to provide a single point of access to profile data.
 * It serves as the bridge between the application's UI and the Firestore 'profiles' collection.
 * </p>
 * <p>
 * As a {@link Model}, it maintains a local cache of {@link Profile} objects that is kept in sync
 * with the database via the {@link DBListener} interface. It handles looking up users by both
 * their database ID and their unique device ID.
 * </p>
 */
public class ProfileManager extends Model implements DBListener<Profile> {
    private static final String TAG = "ProfileManager";
    private List<Profile> profiles = new ArrayList<>();
    private final DBConnector<Profile> connector = new DBConnector<>("profiles", this, Profile.class);

    // Singleton
    private static final ProfileManager manager = new ProfileManager();

    /**
     * Gets the singleton instance of the ProfileManager.
     *
     * @return The single, static instance of ProfileManager.
     */
    public static ProfileManager getInstance() { return manager; }

    // Profile getters

    /**
     * Retrieves the local cache of all user profiles.
     *
     * @return A list of all {@link Profile} objects currently held by the manager.
     */
    @NonNull
    public List<Profile> getProfiles() {
        return profiles;
    }

    /**
     * Finds and retrieves a profile by its unique Firestore document ID.
     * <p>
     * Note: This searches for the internal ID generated by Firestore, not the device ID.
     * </p>
     *
     * @param id The Firestore document ID of the profile. Cannot be null.
     * @return The {@link Profile} object with the matching ID, or {@code null} if no profile is found.
     */
    @Nullable
    public Profile getProfileByDBID(@NonNull String id) {
        for (Profile profile : profiles) {
            // Safe comparison
            if (id.equals(profile.getId())) {
                return profile;
            }
        }
        return null;
    }

    /**
     * Finds and retrieves a profile by the user's unique device ID.
     * <p>
     * This is the primary method for identifying users within the application logic,
     * as the device ID serves as the user's login credential.
     * </p>
     *
     * @param deviceId The unique device ID associated with the profile. Cannot be null.
     * @return The {@link Profile} object with the matching device ID, or {@code null} if no profile is found.
     */
    @Nullable
    public Profile getProfileByDeviceId(@NonNull String deviceId) {
        for (Profile profile : profiles) {
            // Check for null to prevent crashes on malformed data
            if (profile.getDeviceId() != null && profile.getDeviceId().equals(deviceId)) {
                return profile;
            }
        }
        return null;
    }

    /**
     * Checks if a profile associated with a given device ID exists.
     *
     * @param deviceId The device ID to check for. Cannot be null.
     * @return {@code true} if a profile with the specified device ID exists, {@code false} otherwise.
     */
    public boolean doesProfileExist(@NonNull String deviceId) {
        return getProfileByDeviceId(deviceId) != null;
    }

    // Create, update, delete operations

    /**
     * Asynchronously creates a new profile in the Firestore database.
     *
     * @param profile The {@link Profile} object to create. Cannot be null.
     */
    public void createProfile(@NonNull Profile profile) {
        connector.createAsync(profile);
    }

    /**
     * Asynchronously updates an existing profile in the Firestore database.
     *
     * @param profile The {@link Profile} object with updated data. Its ID must be set. Cannot be null.
     */
    public void updateProfile(@NonNull Profile profile) {
        connector.updateAsync(profile);
    }

    /**
     * Asynchronously deletes a profile from the Firestore database.
     * <p>
     * <b>Note:</b> When a profile is deleted, care should be taken to remove the user
     * from any events they have joined. This logic is handled by {@link EventManager#removeFromAllEvents(String)}.
     * </p>
     *
     * @param profile The {@link Profile} object to delete. Its ID must be set. Cannot be null.
     */
    public void deleteProfile(@NonNull Profile profile) {
        connector.deleteAsync(profile);
    }

    /**
     * Callback method invoked by {@link DBConnector} when the profile data changes in Firestore.
     * <p>
     * It updates the local profile cache with the fresh list and immediately notifies
     * all registered views via {@link #notifyViews()} to refresh the UI.
     * </p>
     *
     * @param objects The updated list of {@link Profile} objects from Firestore.
     */
    @Override
    public void readAllAsync_Complete(@NonNull List<Profile> objects) {
        Log.d(TAG, "ProfileManager read all complete, notifying views");
        profiles = objects;
        // Notify views of profile changes
        notifyViews();
    }
}