package com.example.matrix_events.entities;

import androidx.annotation.NonNull;

import com.example.matrix_events.database.DBObject;

import java.io.Serializable;

/**
 * Represents a user profile within the Matrix Events application.
 * <p>
 * This entity class stores all user-related information, including personal details
 * (name, email, phone), system identifiers (device ID, FCM token), and application-specific
 * settings (notification preferences, admin status).
 * </p>
 * <p>
 * It extends {@link DBObject} to facilitate Firestore database operations and implements
 * {@link Serializable} to allow Profile objects to be passed between Activities and Fragments
 * via Intents.
 * </p>
 */
public class Profile extends DBObject implements Serializable {

    // Attribute Declarations
    private String name;
    private String email;
    private String phoneNumber; // optional, can be null
    private String deviceId;
    private String profilePictureUrl;
    private String profilePictureFileName;
    private String FCMToken = "";

    // Profile Notification Preferences
    // Notifications on by Default
    private boolean pushAdminNotifications = true;
    private boolean pushOrganizerNotifications = true;

    private boolean isAdmin = false;

    /**
     * Default constructor required for Firestore data mapping.
     * <p>
     * Firestore needs a public no-argument constructor to deserialize database documents
     * into Java objects.
     * </p>
     */
    public Profile() {}

    /**
     * Constructs a new Profile with the specified mandatory information.
     * <p>
     * Initializes a new user profile with their personal details and device identifier.
     * It also initializes optional fields (like profile pictures) to safe default values.
     * </p>
     *
     * @param name        The full display name of the user. Cannot be null.
     * @param email       The email address of the user. Cannot be null.
     * @param phoneNumber The user's phone number. This field is optional and can be null.
     * @param deviceId    The unique Android Device ID associated with this user. Cannot be null.
     */
    public Profile(@NonNull String name, @NonNull String email, String phoneNumber, @NonNull String deviceId) {
        this.name = name;
        this.email = email;
        this.phoneNumber = phoneNumber;
        this.deviceId = deviceId;

        // Safe defaults for new fields
        this.profilePictureUrl = "";
        this.profilePictureFileName = "";
    }

    // Getters and Setters

    /**
     * Gets the user's display name.
     *
     * @return The name of the user.
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the user's display name.
     *
     * @param name The new name to set. Cannot be null.
     */
    public void setName(@NonNull String name) {
        this.name = name;
    }

    /**
     * Gets the user's email address.
     *
     * @return The email address string.
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the user's email address.
     *
     * @param email The new email address. Cannot be null.
     */
    public void setEmail(@NonNull String email) {
        this.email = email;
    }

    /**
     * Gets the user's phone number.
     *
     * @return The phone number string, or null if not set.
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * Sets the user's phone number.
     *
     * @param phoneNumber The phone number to set. Can be null.
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    /**
     * Gets the unique device ID associated with this profile.
     *
     * @return The Android Device ID string.
     */
    public String getDeviceId() {
        return deviceId;
    }

    /**
     * Gets the Firebase Cloud Messaging (FCM) token for this user.
     * This token is used to send push notifications to this specific device.
     *
     * @return The FCM token string.
     */
    public String getFCMToken() { return FCMToken; }

    /**
     * Sets the Firebase Cloud Messaging (FCM) token.
     *
     * @param FCMToken The new FCM token generated by Firebase Messaging Service.
     */
    public void setFCMToken(String FCMToken) { this.FCMToken = FCMToken; }

    /**
     * Checks if the user has opted to receive push notifications from Admins.
     *
     * @return {@code true} if allowed, {@code false} otherwise.
     */
    public boolean isPushAdminNotifications() {
        return pushAdminNotifications;
    }

    /**
     * Sets the preference for receiving push notifications from Admins.
     *
     * @param pushAdminNotifications The boolean preference value.
     */
    public void setPushAdminNotifications(boolean pushAdminNotifications) {
        this.pushAdminNotifications = pushAdminNotifications;
    }

    /**
     * Checks if the user has opted to receive push notifications from Organizers.
     *
     * @return {@code true} if allowed, {@code false} otherwise.
     */
    public boolean isPushOrganizerNotifications() { return pushOrganizerNotifications; }

    /**
     * Sets the preference for receiving push notifications from Organizers.
     *
     * @param pushOrganizerNotifications The boolean preference value.
     */
    public void setPushOrganizerNotifications(boolean pushOrganizerNotifications) {
        this.pushOrganizerNotifications = pushOrganizerNotifications;
    }

    /**
     * Checks if the current user has Administrator privileges.
     *
     * @return {@code true} if the user is an admin, {@code false} otherwise.
     */
    public boolean isAdmin() { return isAdmin; }

    /**
     * Grants or revokes Administrator privileges for this user.
     *
     * @param admin {@code true} to grant admin status, {@code false} to revoke.
     */
    public void setAdmin(boolean admin) { isAdmin = admin; }

    /**
     * Gets the download URL for the user's profile picture.
     *
     * @return The URL string of the profile picture.
     */
    public String getProfilePictureUrl() { return profilePictureUrl; }

    /**
     * Sets the profile picture URL.
     * <p>
     * Includes a safety check: if the provided URL is null, it defaults to an empty string
     * to prevent null pointer exceptions in the UI.
     * </p>
     *
     * @param profilePictureUrl The URL string to set.
     */
    public void setProfilePictureUrl(String profilePictureUrl) {
        this.profilePictureUrl = (profilePictureUrl == null) ? "" : profilePictureUrl;
    }

    /**
     * Gets the filename of the user's profile picture stored in cloud storage.
     *
     * @return The filename string.
     */
    public String getProfilePictureFileName() { return profilePictureFileName; }

    /**
     * Sets the filename of the user's profile picture.
     *
     * @param profilePictureFileName The filename string to set.
     */
    public void setProfilePictureFileName(String profilePictureFileName) {
        this.profilePictureFileName = profilePictureFileName;
    }
}